language: node_js
node_js:
  - lts/*
install:
  - npm ci # npm ci
script:
  - npm run docs:build # npm run docs:build
# after_script:
#   - cd docs/.vuepress/dist
#   - git init
#   - git add -A
#   - git commit -m 'deploy'
#   - git config user.name  $USERNAME
#   - git config user.email $EMAIL
#   - git push -f $REF $BRANCH:$BRANCH
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  repo: $REF
  email: $EMAIL
  name: $USERNAME
  target_branch: $BRANCH
  github_token: $GITHUB_TOKEN # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  keep_history: true
  on:
    branch: master
